# 让 module 里的 drivers / libs 参与编译
CONFIG_SKYWALKER_DRIVER_IMU=y
CONFIG_SKYWALKER_DRIVER_KALMAN_FILTER=y
CONFIG_SKYWALKER_DRIVER_PID=y
CONFIG_SKYWALKER_LIB_MATRIX=y
CONFIG_SKYWALKER_LIB_VOFA=y
CONFIG_UART_ASYNC_API=y
CONFIG_NOCACHE_MEMORY=y
