CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SKYWALKER_REFEREE=y
CONFIG_COMMAND_GIMBAL_REFEREE=y
CONFIG_SKYWALKER_VISION=y
CONFIG_SKYWALKER_VISION_AB=y
CONFIG_SKYWALKER_VISION_RECEIVER=y
CONFIG_COMMAND_GIMBAL_VISION_EXECUTE=y
CONFIG_SKYWALKER_IMU=y
CONFIG_SKYWALKER_IMU_RECEIVER=y
CONFIG_SKYWALKER_IMU_DM_RS485=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
